title: cyber·Fund API
version: v1
protocols: [ HTTPS ]
baseUri: http://api.cyber.fund/{version}
mediaType: application/json
types:
  Block:
    type: object
    properties:
      hash:
        required: true
        type: string
      timestamp:
        required: true
        type: timestamp
      type:
        required: false
        type: string
