title: cyber·Fund API
version: v1
protocols: [ HTTPS ]
baseUri: http://api.cyber.fund/{version}
mediaType: application/json
types:
  Transaction:
    type: object
    properties:
      hash:
        required: true
        type: string
      system_type: #auto or #manual
        required: true
        type: boolean
      reporter:
        required: true
        type: object
      timestamp:
        required: true
        type: datetime
      refference:
        required: false
        type: string
      description:
        required: false
        type: string
      from:
        required: true
        type: object
      to:
        required: true
        type: object
      token:
        required: true
        type: object
      amount:
        required: true
        type: integer
      btc_valuation:
        required: false
        type: integer
      usd_valuation:
        required: false
        type: integer
